import type { Route as _IndexRoute } from '../pages/';
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _AboutRoute } from '../pages/about';
import type { Route as _CaptureRoute } from '../pages/capture';
import type { Route as _CompareRoute } from '../pages/compare';
import type { Route as _TimelineRoute } from '../pages/timeline';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/capture': (typeof _CaptureRoute)['_inputType'];
    '/compare': (typeof _CompareRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/timeline': (typeof _TimelineRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/capture': (typeof _CaptureRoute)['_outputType'];
    '/compare': (typeof _CompareRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/timeline': (typeof _TimelineRoute)['_outputType'];
  }
}
